services:
  # MongoDB for User Service (optional)
  user-mongo:
    # image: mongo:latest
    image: mongo:6-jammy
    container_name: ${USER_MONGO_HOST}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${USER_MONGO_PASSWORD}
      TZ: "Europe/Moscow"
    volumes:
      - user-mongo-data:/data/db
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 10s
      retries: 5

  # User Service Postgres
  user:
    build: ./${USER_PATH}
    container_name: ${USER_CONTAINER_NAME}
    ports:
      - ${USER_EXPOSED_PORT}:${USER_LOCAL_PORT}
    depends_on:
      user-mongo:
        condition: service_healthy
      # - user-mongo
    environment:
      MONGO_URI: mongodb://${USER_MONGO_USER}:${USER_MONGO_PASSWORD}@${USER_MONGO_HOST}:${USER_MONGO_PORT}/${USER_MONGO_DBNAME}
    networks:
      - backend
    volumes:
      - ./config.toml:/app/config.toml
      - ./logs:/app/logs
    restart: on-failure

volumes:
  user-mongo-data:
