services:
  postgres:
    image: postgres:13
    container_name: auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
      TZ: "Europe/Moscow"
    ports:
      - "5002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations/sql:/migrations
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - local-network
    entrypoint: ["migrate", "-path=/migrations", "-database", "postgres://postgres:password@auth-postgres:5432/auth_db?sslmode=disable", "up"]

  auth-service:
    container_name: authservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - local-network
      - shared-network
    environment:
      DATABASE_HOST: auth-postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: auth_db
      DATABASE_SSLMODE: disable
    volumes:
      - ../config.toml:/app/config.toml
      - ../logs:/app/logs
    command: ["./main"]

volumes:
  postgres_data:

networks:
  local-network:
  shared-network:
    external: true
